#configuration file version
#do not change
version: 1

#language
general:
  language: "english"
  prefix: "§l§7[§cBed§fWars§7]§r§f"
  #Try to automatically join to an arena after player login
  auto_join: false
  #If true, all commands (except the ingame ones) will be disabled for players
  disable_command: true
  #Commands available even in arena.
  #Note that events like teleport (into different worlds) etc aren't handled by BedWars
  enabled_commands: [ "lobby"] #Assuming lobby commands cause player to leave the BedWars server
  #Separate chat between players in game and the others playing on server
  separate_chat: true

data:
  #if disabled, no player data will be saved
  enable: false
  #data providers, default available: [mysql, mongodb], use 'none' to disable
  data_provider: none
  #whether BedWars should use DbLib plugin (if available)
  use_db_lib: true
  #unique player identifier. Can be whether 'name' or 'uuid'. UUID is recommended unless you're running server in offline mode
  player_identifier: uuid
  #Attempt to load arenas from the specified data source
  load_arenas: false
  #in case you don't use dblib:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: mysql
    database: default
  mongodb:
    host: 127.0.0.1
    port: 27017
    user: root
    password: mongodb
    database: default
    #additional mongo options
#    options:
#      opt1: val1
#      op2: val2

economy:
  economy_provider: none
  rewards:
    #    For economy systems with multiple currencies you can specify the currency like that, else the default (or random) one will be chosen
    #    kills:
    #      coin: 10 #currency 'coin'
    #      token: 3 #currency 'token'
    kills: 0
    wins: 0
    #on bed destroyed
    beds: 0
    #per game played
    games: 0

synapse:
  #If enabled, player will be transferred to the lobby server instead of kicked out of the game
  transfer: true