name: BedWars
version: "1.0"
api: ["1.0.0"]
main: com.creeperface.nukkit.bedwars.BedWars
author: "CreeperFace"
description: "bedWars minigame"
depend: ["Actaeon", "DbLib", "PlaceholderAPI", "KotlinLib"]
softdepend: ["BedWarsHelper"]

permissions:
  bedwars:
    default: op
    description: "Allows player to perform all actions"
    children:
      bedwars.command:
        default: op
        description: "Allows player to use all commands"
        children:
          bedwars.command.vote:
            default: true
            description: "Allows player to use vote command"
          bedwars.command.stats:
            default: true
            description: "Allows player to see their game stats"
          bedwars.command.stats.others:
            default: false
            description: "Allows player to see others game stats"
          bedwars.command.start:
            default: op
            description: "Allows player to use start command"
          bedwars.command.stop:
            default: op
            description: "Allows player to use stop command"
          bedwars.command.quickjoin:
            default: op
            description: "Allows player to use quickjoin command"
          bedwars.command.sign:
            default: op
            description: "Allows player to use sign command"

      bedwars.sign:
        default: op
        description: "Allows player to use bedwars signs"
      bedwars.joinfullarena:
        default: op
        description: "Allows player to join full arenas"
      bedwars.joinfullteam:
        defaul: op
        description: "Allows player to join full teams"
      bedwars.crossplatform:
        default: op
        description: "Allows player to join platform-specific arenas"